LinZui520/website

README.md

It will help you to solve kinds of question in the different scenes.

docs: 完善README

---

README.md

Revert "docs: 完善README"

---

README.md

It will help you to protect the wholeness of installing.

docs: perfect README

---

web/src/components/article/Comment.tsx

当未登录时 评论框无法显示头像
故设置当未登录时 不会显示评论框

fix: 未登录 评论区头像bug

---

server/service/article.go
server/service/comment.go
server/service/images.go
server/service/message.go
server/service/user.go
web/src/pages/Info.tsx
web/src/pages/admin/ArticleManager.tsx
web/src/pages/admin/ImageManager.tsx
web/src/pages/admin/IndexAdmin.tsx
web/src/pages/admin/UserManager.tsx

feat: 更改用户权限系统

---

web/src/hooks/article/useManageArticle.ts
web/src/hooks/comment/useManagerComment.ts
web/src/hooks/image/useManageImage.ts
web/src/hooks/message/useManageMessage.ts

fix: 控制台权限 bug

---

server/service/conversation.go
web/src/hooks/useChat.ts

设置客户端每32秒ping一下服务端 并回复消
保持聊天室会话不会被关闭

feat: 保持聊天室长连接

---

server/service/conversation.go
web/src/hooks/useChat.ts

将代码中`if else`转为`switch case`
使代码可读性变高

refactor: 重构聊天室部分代码

---

web/package-lock.json
web/package.json

revert: "chore(deps): bump @vavt/rt-extension from 1.1.1 to 1.2.2 in /web"

---

web/package-lock.json
web/package.json

chore(deps): bump @vavt/rt-extension from 1.1.1 to 1.2.2 in /web

---

web/src/components/index/ScrollBar.tsx
web/src/pages/Article.tsx
web/src/pages/Articles.tsx

feat: 给部分界面添加滚动栏

---

web/package-lock.json
web/package.json
web/src/components/articles/ArticlesMain.tsx

fix: blog bug

---

web/src/pages/Home.tsx

feat: Add End in Home

---

web/src/components/memories/21/End.tsx
web/src/components/memories/21/Ninth.tsx

fix: End picture bug,and beautify The Ninth and End

---

web/src/components/memories/21/Ninth.tsx

feature: 完结撒花

---

fullstack/package-lock.json
fullstack/package.json

revert: "chore(deps-dev): bump eslint from 8.57.0 to 9.2.0 in /fullstack"

---

web/src/components/(web)/Footer.tsx

feature : 更新footer

---

web/src/app/(web)/linzui/page.tsx

feat: linzui主页

---

web/src/app/(web)/linzui/page.tsx

feat: Linzui front page

---

web/src/app/(web)/linzui/layout.tsx
web/src/app/(web)/linzui/page.tsx

feat: add Linzui layout
